---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-14.04
  driver_config:
    box: opscode-ubuntu-14.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-14.04_provisionerless.box
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box

suites:
- name: bare
  run_list:
    - recipe[gem_server::default]
  attributes:

- name: nginx
  run_list:
    - recipe[gem_server::default]
    - recipe[gem_server::proxy]
  attributes:

- name: rubygems_proxy
  run_list:
    - recipe[gem_server::default]
  attributes:
    gem_server:
      rubygems_proxy: true
      allow_remote_failure: true

- name: auth
  run_list:
    - recipe[gem_server::default]
  attributes:
    gem_server:
      authentication:
        readers:
          joe: "read"
        writers:
          bob: "write"
